### ISSUE TITLE
['hash_salt'] error

### ISSUE THREAD

**Issue by khushbooraj** [letusdo/2020#5]
Hi, 
PFA and fix this issue.

![Screenshot from 2020-01-03 16-44-56](https://user-images.githubusercontent.com/56381518/71720658-785b6500-2e48-11ea-80ce-e6905ac28f43.png)

**Comment by hena78600** [comment]
['hash_salt'] error can be solved while adding hash_code in settings.php.
First add database, username, password of your own in settings.php and qL6mQ9lx_3ZfuDo56y11LfGt9qBf4wT_oWcDa_l1AyxjY4zIAXLYKncY175ybAqsh-HJ5qrFiw in the place of hash_code in settings.php.
